research_task:
  description: >
    Conduct a thorough research on the assets for the following two Cardano addresses:

    Address 1: {cardano_address_1}
    Address 2: {cardano_address_2}

    Make sure you find information about all assets each address holds.
    Use the Kupo API to get the exact amount of Cardano Native Assets that each address has.
  expected_output: >
    The exact amount of Cardano Native Assets that each address has in the following format:

    <cardano_address_1> holds the following assets:
    1- lovelace - <amount_of_lovelace_for_address_1>
    2- <asset_1_key> - <amount_of_asset_1_for_address_1>
    3- <asset_2_key> - <amount_of_asset_2_for_address_1>
    4- ...and so on

    <cardano_address_2> holds the following assets:
    1- lovelace - <amount_of_lovelace_for_address_2>
    2- <asset_1_key> - <amount_of_asset_1_for_address_2>
    3- <asset_2_key> - <amount_of_asset_2_for_address_2>
    4- ...and so on

    Make sure you include all assets each address holds.
  agent: researcher

reporting_task:
  description: >
    Review the information you received from each address about the assets they hold.
    Create a JSON report. This JSON report should present the assets each address holds. For each address,
    also include a funny comment about the assets they hold. Make sure the comment is not too long.
    The report should be consistently formated with JSON and in a way that is easy to understand for a non-technical audience.
  expected_output: >
    A JSON report that presents the assets each address holds.
    Formatted as JSON without '```'
  agent: reporting_analyst
